name: wildness_ui_golden_toolkit
description: "A tools for create goldent test on wildness components."

repository: https://github.com/coolosos/wildness_ui
issue_tracker: https://github.com/coolosos/wildness_ui/issues
homepage: https://github.com/coolosos

version: 0.1.1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0
  collection: ^1.18.0
  equatable: ^2.0.5
  nested: ^1.0.0
  universal_io: ^2.2.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.4.9
  golden_toolkit: ^0.15.0

  wildness_ui: ^0.1.1

dev_dependencies:
  coolint: ^2.0.0
