name: wildness_ui
description: "A components with Kind provider."

repository: https://github.com/coolosos/wildness_ui
issue_tracker: https://github.com/coolosos/wildness_ui/issues
homepage: https://github.com/coolosos

version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.11.0
  collection: ^1.18.0
  equatable: ^2.0.5
  nested: ^1.0.0
  universal_io: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  coolint: 2.0.0
